AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'
  
  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  ApiDnsName:
    Type: String
    Description: 'The DNS name used for B2B rest API.'

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'

  IoApiDnsName:
    Type: String
    Description: 'The DNS name used for IO rest API.'

  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'

  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'

  UserAttributesTableName:
    Type: String
    Description: 'Name of dynamodb table containing User Attributes information'

  UserAttributesTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing User Attributes information'

  ExternalChannelBaseUrl:
    Type: String
    Description: 'Base url of external channel microservice'

  HeaderValueExternalChannelCxId:
    Type: String
    Description: 'Header di riconoscimento per external channel'

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  UserAttributesActionsQueueName:
    Type: String
    Description: 'Send and pull actions'
  
  UserAttributesActionsQueueARN:
    Type: String
    Description: 'Send and pull actions'

  UserAttributesActionsQueueAlarmARN:
    Type: String
    Description: pn-user-attributes-actions input queue alarm ARN

  UserAttributesActionsQueueAgeAlarmARN:
    Type: String
    Description: pn-user-attributes-actions input queue age alarm ARN

  ExternalChannels2UserAttributesQueueName:
    Type: String
    Description: 'external channels to user attributes queue name'
  
  ExternalChannels2UserAttributesQueueARN:
    Type: String
    Description: 'external channels to user attributes queue ARN'

  ExternalChannels2UserAttributesQueueAlarmARN:
    Type: String
    Description: external channels to user attributes queue alarm ARN

  ExternalChannels2UserAttributesQueueAgeAlarmARN:
    Type: String
    Description: external channels to user attributes queue age alarm ARN

  IoActivationSendOlderThanDays:
    Type: String
    Description: 'Parametro per il toc toc di Io'

  AooUoSenderID:
    Type: String
    Description: 'Parametro per elenco di Id AOO/UO con domicili/recapiti pre rilascio'

  VerificationCodeLegalTTL:
    Type: String
    Description: 'Parametro durata massima per validazione per messaggi di tipo legal'

  VerificationCodeCourtesyTTL:
    Type: String
    Description: 'Parametro durata massima per validazione per messaggi di cortesia'

  ValidationCodeMaxAttempts:
    Type: String
    Description: 'Parametro numero massimo di tentativi di validazione'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'

  AlbSecurityGroup:
    Type: String
    Description: 'Application load balancer security group'

  UserAttributesTableEncryptKeyId:
    Type: String
    Description: 'Key per dynamodb'

  # OpenApi Bucket params
  MicroserviceBucketName:
    Type: String
    Default: ''
    Description: 'Name of the bucket where the microservice files are copied during deploy'

  MicroserviceBucketBaseKey:
    Type: String
    Default: ''
    Description: 'Base key of the microservice in the s3 bucket'

  # Log group parameters
  EcsLogGroup:
    Type: String
    Description: 'Ecs log group name'

  # Heath Check parameters
  HealthCheckInterval:
    Description: Seconds between two health check
    Type: Number
    Default: 60

  HealthCheckTimeout:
    Description: health check timeout seconds
    Type: Number
    Default: 5
  
  HealthyThresholdCount:
    Description: |
      The number of consecutive health checks successes required before considering 
      an unhealthy target healthy. 
    Type: Number
    Default: 5
  
  UnhealthyThresholdCount:
    Description: |
      The number of consecutive health check failures required before considering a target unhealthy. 
    Type: Number
    Default: 2

  # Instance parameters
  # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
  # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
  # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
  # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
  # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
  CpuValue:
    Type: Number
    Default: 1024
    Description: Fargate virtual CPU quantity 1024 equals one vCPU

  # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
  # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
  # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
  # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
  # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
  MemoryAmount:
    Type: String
    Default: 2GB
    Description: memory amount reserved to the task pod.
    AllowedValues: [ 2GB, 4GB, 6GB, 8GB ]

  # Autoscaling parameters
  AutoscalingCheckPeriod:
    Default: 60
    Type: Number
    Description: minimum autoscaling number of tasks\

  AutoscalingDataPointN:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingDataPointM:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingThreshold:
    Default: 70
    Type: String
  
  MinTasksNumber:
    Default: 1
    Type: Number
    Description: minimum autoscaling number of tasks

  MaxTasksNumber:
    Default: 6
    Type: Number
    Description: maximum autoscaling number of tasks 

  LogAlarmStrategy:
    Type: String
    Default: 'FATAL'

  IOBackendCidrs:
    Type: String
    Default: ''

  WebApiLimit:
    Type: Number
    Default: 600
    Description: WEB api WAF Limit (per IP)

  EnhancedWebSecurityEnabled:
    Type: String
    Default: false
    Description: Enable additional WAF Web rules
    AllowedValues:
      - true
      - false

Conditions:
  UseExternalChannelMock: !Equals [ !Ref ExternalChannelBaseUrl, "Mock" ]

Resources:

  # PN-User-Attributes microservice
  UserAttributesMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-user-attributes'
        CpuValue: !Ref CpuValue
        MemoryAmount: !Ref MemoryAmount
        HealthCheckTimeout: !Ref HealthCheckTimeout
        HealthCheckInterval: !Ref HealthCheckInterval
        HealthyThresholdCount: !Ref HealthyThresholdCount
        UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
        AutoscalingStrategy: REST-API
        AutoscalingThreshold: !Ref AutoscalingThreshold
        AutoscalingCheckPeriod: !Ref AutoscalingCheckPeriod
        MinTasksNumber: !Ref MinTasksNumber
        MaxTasksNumber: !Ref MaxTasksNumber
        AutoscalingDataPointN: !Ref AutoscalingDataPointN
        AutoscalingDataPointM: !Ref AutoscalingDataPointM
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'CORS_ALLOWED_DOMAINS=${CorsAllowedDomains}'
        ContainerEnvEntry3: !Sub 'PN_USER_ATTRIBUTES_DYNAMODB_TABLE_NAME=${UserAttributesTableName}'
        ContainerEnvEntry4: 'PN_USER_ATTRIBUTES_CLIENT_DATAVAULT_BASEPATH=http://alb.confidential.pn.internal:8080'
        ContainerEnvEntry5:
          Fn::If:
            - UseExternalChannelMock
            - !Sub 'PN_USER_ATTRIBUTES_CLIENT_EXTERNALCHANNELS_BASEPATH=http://${ApplicationLoadBalancerDomain}:8080'
            - !Sub 'PN_USER_ATTRIBUTES_CLIENT_EXTERNALCHANNELS_BASEPATH=${ExternalChannelBaseUrl}'
        ContainerEnvEntry6: !Sub 'PN_USER_ATTRIBUTES_CLIENT_EXTERNALCHANNELS_HEADER_EXTCH_CX_ID=${HeaderValueExternalChannelCxId}'
        ContainerEnvEntry7: !Sub 'PN_USER_ATTRIBUTES_CLIENT_EXTERNALREGISTRY_BASEPATH=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry8: !Sub 'PN_USER_ATTRIBUTES_CLIENT_DELIVERY_BASEPATH=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry9: !Sub 'PN_USER_ATTRIBUTES_IOACTIVATIONSENDOLDERTHANDAYS=${IoActivationSendOlderThanDays}'
        ContainerEnvEntry10: !Sub 'SPRING_CLOUD_FUNCTIONROUTER_QUEUES_LIST=${UserAttributesActionsQueueName},${ExternalChannels2UserAttributesQueueName}'
        ContainerEnvEntry11: !Sub 'PN_USER_ATTRIBUTES_TOPICS_ACTIONS=${UserAttributesActionsQueueName}'
        ContainerEnvEntry12: !Sub 'PN_USER_ATTRIBUTES_VALIDATIONCODEMAXATTEMPTS=${ValidationCodeMaxAttempts}'
        ContainerEnvEntry13: !Sub 'PN_USER_ATTRIBUTES_VERIFICATIONCODELEGALTTL=${VerificationCodeLegalTTL}'
        ContainerEnvEntry14: !Sub 'PN_USER_ATTRIBUTES_VERIFICATIONCODECOURTESYTTL=${VerificationCodeCourtesyTTL}'
        ContainerEnvEntry15: !Sub 'PN_USER_ATTRIBUTES_TOPICS_FROMEXTERNALCHANNEL=${ExternalChannels2UserAttributesQueueName}'
        ContainerEnvEntry16: !Sub 'PN_USER_ATTRIBUTES_AOOUOSENDERID=${AooUoSenderID}'
        MappedPaths: '/user-consents/*,/address-book/*,/address-book-private/*,/address-book-io/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        AlbSecurityGroup: !Ref AlbSecurityGroup
        TaskRoleManagedPolicyArn: !Ref UserAttributesMicroserviceTaskManagedPolicy
        EcsLogGroup: !Ref EcsLogGroup
        LogAlarmStrategyV1: !Ref LogAlarmStrategy

  UserAttributesMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ExecuteTransaction
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:TransactGetItems
              - dynamodb:TransactWriteItems
              - dynamodb:UpdateItem
            Resource:
              - !Ref UserAttributesTableArn
              - !Sub "${UserAttributesTableArn}/*"
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:ChangeMessageVisibilityBatch
              - sqs:DeleteMessage
              - sqs:DeleteMessageBatch
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:SendMessageBatch
            Resource:
              - !Ref UserAttributesActionsQueueARN
              - !Ref ExternalChannels2UserAttributesQueueARN
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
            Resource:
              - !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${UserAttributesTableEncryptKeyId}

  # Expose PN-user-attributes microservice public API with API-GW for WEB usage
  UserAttributesMicroservicePublicWebAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service-openapi.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-user-attributes'
        IntendedUsage: WEB
        DnsName: !Ref WebApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'user-consents'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn        
        OpenApiBucketName: !Ref MicroserviceBucketName
        OpenApiBucketKey: !Sub ${MicroserviceBucketBaseKey}/docs/openapi/aws/api-user-consents-WEB-aws.yaml

  UserAttributesMicroservicePublicWebApiWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-user-attributes-web'
        IntendedUsage: WEB
        APIGatewayARNs: !GetAtt UserAttributesMicroservicePublicWebAPI.Outputs.APIGatewayARN
        Limit: !Ref WebApiLimit
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        EnhancedWebSecurityEnabled: !Ref EnhancedWebSecurityEnabled

  # Expose PN-AddressBook microservice public API with API-GW for WEB usage
  AddressBookMicroservicePublicWebAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service-openapi.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-address-book'
        IntendedUsage: WEB
        DnsName: !Ref WebApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'address-book'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn    
        OpenApiBucketName: !Ref MicroserviceBucketName
        OpenApiBucketKey: !Sub ${MicroserviceBucketBaseKey}/docs/openapi/aws/api-address-book-WEB-aws.yaml

  AddressBookMicroservicePublicWebApiWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-address-book-web'
        IntendedUsage: WEB
        APIGatewayARNs: !GetAtt AddressBookMicroservicePublicWebAPI.Outputs.APIGatewayARN
        Limit: !Ref WebApiLimit
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        EnhancedWebSecurityEnabled: !Ref EnhancedWebSecurityEnabled

  # Expose PN-AddressBook microservice public API with API-GW for IO Backend usage
  AddressBookMicroservicePublicIoAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service-openapi.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-address-book-io'
        IntendedUsage: IO
        DnsName: !Ref IoApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'address-book-io'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn    
        OpenApiBucketName: !Ref MicroserviceBucketName
        OpenApiBucketKey: !Sub ${MicroserviceBucketBaseKey}/docs/openapi/aws/api-address-book-io-IO-aws.yaml

  AddressBookMicroservicePublicIoApiWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-address-book-io'
        IntendedUsage: IO
        APIGatewayARNs: !GetAtt AddressBookMicroservicePublicIoAPI.Outputs.APIGatewayARN
        AllowedCidrs: !Ref IOBackendCidrs

  ## Dashboard
  UserAttributesMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-user-attributes"
        DynamoDBTableNames: !Join 
          - ',' 
          - - !Ref UserAttributesTableName 
        RestApiStageArns: !Join
          - ','
          - - !GetAtt UserAttributesMicroservicePublicWebAPI.Outputs.RestApiStageArn
            - !GetAtt AddressBookMicroservicePublicWebAPI.Outputs.RestApiStageArn
            - !GetAtt AddressBookMicroservicePublicIoAPI.Outputs.RestApiStageArn
        RestApiNames: !Join
          - ','
          - - !GetAtt UserAttributesMicroservicePublicWebAPI.Outputs.RestApiName
            - !GetAtt AddressBookMicroservicePublicWebAPI.Outputs.RestApiName
            - !GetAtt AddressBookMicroservicePublicIoAPI.Outputs.RestApiName
        AlarmArns: !Join
          - ','
          - - !GetAtt UserAttributesMicroservice.Outputs.FatalLogsMetricAlarmArn
            - !GetAtt UserAttributesMicroservicePublicWebAPI.Outputs.RestApiErrorAlarmArn
            - !GetAtt AddressBookMicroservicePublicWebAPI.Outputs.RestApiErrorAlarmArn
            - !GetAtt AddressBookMicroservicePublicIoAPI.Outputs.RestApiErrorAlarmArn
            - !GetAtt UserAttributesMicroservicePublicWebAPI.Outputs.RestApiLatencyAlarmArn
            - !GetAtt AddressBookMicroservicePublicWebAPI.Outputs.RestApiLatencyAlarmArn
            - !GetAtt AddressBookMicroservicePublicIoAPI.Outputs.RestApiLatencyAlarmArn
            - !Ref UserAttributesActionsQueueAlarmARN
            - !Ref ExternalChannels2UserAttributesQueueAlarmARN
            - !Ref UserAttributesActionsQueueAgeAlarmARN
            - !Ref ExternalChannels2UserAttributesQueueAgeAlarmARN
        QueueArns: !Join
          - ','
          - - !Ref UserAttributesActionsQueueARN
            - !Ref ExternalChannels2UserAttributesQueueARN
        LogGroupsNames: !Join
          - ','
          - - !Sub '/aws/ecs/${ProjectName}-user-attributes'
