AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
   
  UserAttributesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-UserAttributes'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true 
      Tags:
        - Key: pnInfraFeature
          Value: pnStorage
        - Key: pnMicroservice
          Value: !Sub '${ProjectName}-UserAttributes'
          
  UserAttributesActionsQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-user-attributes-actions'
        DelaySeconds: 1

Outputs:

  # Actions Queue parameters
  UserAttributesActionsQueueName:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.QueueName
    Description: pn-user-attributes-actions input queue name
  UserAttributesActionsQueueURL:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.QueueURL
    Description: pn-user-attributes-actions input queue URL
  UserAttributesActionsQueueARN:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.QueueARN
    Description: pn-user-attributes-actions input queue ARN
  UserAttributesActionsQueueAlarmARN:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.SqsDLQAlarmArn
    Description: pn-user-attributes-actions input queue alarm ARN
  UserAttributesActionsQueueAgeAlarmARN:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.SqsAgeAlarmArn
    Description: pn-user-attributes-actions input queue alarm ARN

  # Table parameters
  UserAttributesTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref UserAttributesTable
  UserAttributesTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${UserAttributesTable.Arn}'