package it.pagopa.pn.user.attributes.exceptions;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;

public class PnUserattributesExceptionCodes extends PnExceptionsCodes {

    // raccolgo qui tutti i codici di errore di user attributes
    public static final String ERROR_CODE_USERATTRIBUTES_DELETE_ADDRESS_FAILED = "PN_USERATTRIBUTES_DELETEADDRESSFAILED";
    public static final String ERROR_CODE_USERATTRIBUTES_ADDRESS_NOT_FOUND = "PN_USERATTRIBUTES_ADDRESSNOTFOUND";
    public static final String ERROR_CODE_USERATTIBUTES_FORBIDDEN = "PN_USERATTRIBUTES_FORBIDDEN";
    public static final String ERROR_CODE_INVALID_VERIFICATION_CODE = "PN_USERATTRIBUTES_INVALIDVERIFICATIONCODE";
    public static final String ERROR_CODE_BADCONFIGURATION_MISSING_TEMPLATE = "PN_USERATTRIBUTES_MISSINGTEMPLATE";
    public static final String ERROR_CODE_MISSING_RECIPIENTID = "PN_USERATTRIBUTES_MISSINGRECIPIENTID";
    public static final String ERROR_CODE_IO_ACTIVATION_FAILED = "PN_USERATTRIBUTES_IOACTIVATIONFAILED";
    public static final String ERROR_CODE_IO_DEACTIVATION_FAILED = "PN_USERATTRIBUTES_IODEACTIVATIONFAILED";
    public static final String ERROR_CODE_IO_ERROR = "PN_USERATTRIBUTES_IOERROR";
    public static final String ERROR_CODE_INVALID_LEGAL_CHANNEL = "PN_USERATTRIBUTES_INVALIDLEGALCHANNEL";
    public static final String ERROR_CODE_INVALID_COURTESY_CHANNEL = "PN_USERATTRIBUTES_INVALIDCOURTESYCHANNEL";
    public static final String ERROR_CODE_USERATTRIBUTES_EVENT_TYPE_MISSING = "ERROR_CODE_USERATTRIBUTES_EVENTTYPEMISSING";
    public static final String ERROR_CODE_USERATTRIBUTES_INVALID_EVENT_TYPE = "ERROR_CODE_USERATTRIBUTES_INVALIDEVENTTYPE";
    public static final String ERROR_CODE_USERATTRIBUTES_INVALID_MESSAGE_HEADERS = "ERROR_CODE_USERATTRIBUTES_INVALIDMESSAGEHEADERS";
}
